# .travis.yml

language: python
python:
    - "3.7"

dist: trusty
sudo: required

env:
    - DJANGO_VERSION==2.1.2

install:
    - pip3 install -q -r requirements.txt

script:
    - cd wintercoding
    - python3 manage.py migrate
    - python3 -m pytest
